spring.main.web-application-type=none

spring.ai.openai.api-key=${AWS_BEARER_TOKEN_BEDROCK}

spring.ai.openai.base-url=https://bedrock-mantle.us-east-2.api.aws/v1
spring.ai.openai.chat.model=openai.gpt-oss-120b

# Not yet generally available
#spring.ai.openai.base-url=https://bedrock-mantle.us-east-2.api.aws/openai/v1
#spring.ai.openai.chat.model=openai.gpt-5.5

agent.skills.paths=classpath:/META-INF/skills
